#ifndef _GBEMG_CONTMACRODEF_H_
#define _GBEMG_CONTMACRODEF_H_


/* 
copyright reserved by 
celtech company Co Ltd,
*/
 


#ifdef __cplusplus
extern "C" {
#endif



#define GBEMG_CONT_SECTION_TABLE_ID_OFFSET (0)
#define GBEMG_CONT_SECTION_LENGTH_OFFSET (1)
#define GBEMG_CONT_EBM_ID_OFFSET (3)
#define GBEMG_CONT_VERSION_NUM_OFFSET (5)
#define GBEMG_CONT_SECTION_NUM_OFFSET (6)
#define GBEMG_CONT_LAST_SECTION_NUM_OFFSET (7)
#define GBEMG_CONT_MULTILINGUAL_NUM_OFFSET (8)


#define GBEMG_CONT_TABLE_HEADER_LENGTH (9)




#define GBEMG_CONT_SECTION_TABLE(buf) (U8)((buf[GBEMG_CONT_SECTION_TABLE_ID_OFFSET]&0xFF))
#define GBEMG_CONT_SECTION_LENGTH(buf) (TS_READ_16(&buf[GBEMG_CONT_SECTION_LENGTH_OFFSET])&0xFFF)

#define GBEMG_CONT_EBM_ID_CONFIRM(buf)   (TS_READ_16(&buf[GBEMG_CONT_EBM_ID_OFFSET])&0xFFFF)

#define GBEMG_CONT_VERSION_NUM(buf)   (U8)((buf[GBEMG_CONT_VERSION_NUM_OFFSET]>>1)&0x1F)

#define GBEMG_CONT_SECTION_NUM(buf)   (U8)(buf[GBEMG_CONT_SECTION_NUM_OFFSET]&0xFF)


#define GBEMG_CONT_LAST_SECTION_NUM(buf) (U8)(buf[GBEMG_CONT_LAST_SECTION_NUM_OFFSET]&0xFF)

#define GBEMG_CONT_MULTILINGUAL_NUM(buf) (U8)(buf[GBEMG_CONT_MULTILINGUAL_NUM_OFFSET]&0x0F)




/*the following macro based on the begining of the loop of the multilingual content */

#define GBEMG_CONTCONT_MULTILINGUAL_CONT_LENGTH_OFFSET (0)

#define GBEMG_CONTCONT_LANGUAGECODE_OFFSET  (2)

#define GBEMG_CONTCONT_CHARACTERSET_OFFSET  (5)

#define GBEMG_CONTCONT_MSGTEXT_LENGTH_OFFSET  (6)



#define GBEMG_CONTCONT_MULTILINGUAL_CONT_LENGTH(buf) (TS_READ_16(&buf[GBEMG_CONTCONT_MULTILINGUAL_CONT_LENGTH_OFFSET])&0xFFFF)

#define GBEMG_CONTCONT_LANGUAGE_CODE(buf)  TS_READ_24(&buf[GBEMG_CONTCONT_LANGUAGECODE_OFFSET])

#define GBEMG_CONTCONT_CHARACTER_SET(buf)  (U8)(buf[GBEMG_CONTCONT_CHARACTERSET_OFFSET]&0x07)

#define GBEMG_CONTCONT_MSGTEXT_LENGTH(buf) (TS_READ_16(&buf[GBEMG_CONTCONT_MSGTEXT_LENGTH_OFFSET])&0xFFFF)

  


/* the following macro based on offset after loop of message test */

#define GBEMG_CONTCONT_AGENCYNAME_LENGTH_OFFSET (0)

#define GBEMG_CONTCONT_AGENCYNAME_LENGTH(buf)  (U8)(buf[GBEMG_CONTCONT_AGENCYNAME_LENGTH_OFFSET]&0xFF)

/* the following macro based on offset after loop of agency name*/

#define GBEMG_CONTCONT_AUXILIARY_NUM_OFFSET (0)

#define GBEMG_CONTCONT_AUXILIARY_DATA_NUM(buf)  (U8)(buf[GBEMG_CONTCONT_AUXILIARY_NUM_OFFSET]&0x0F) 

/* the following macro begin the loop of the auxiliary data */

#define GBEMG_CONTCONT_AUXILIARY_DATA_TYPE_OFFSET (0)

#define GBEMG_CONTCONT_AUXILIARY_DATA_LENGTH_OFFSET (1)

#define GBEMG_CONTCONT_AUXILIARY_DATA_TYPE(buf) (U8)(buf[GBEMG_CONTCONT_AUXILIARY_DATA_TYPE_OFFSET]&0xFF)

#define GBEMG_CONTCONT_AUXILIARY_DATA_LENGTH(buf) (TS_READ_24(&buf[GBEMG_CONTCONT_AUXILIARY_DATA_LENGTH_OFFSET])&0x03FFFF)




#ifdef __cplusplus
}
#endif

#else
#error "Multiple inclusions of gbemg_contentmacro.h"

#endif
