#ifndef _GBEMG_BOXCTLMACRODEF_H_
#define _GBEMG_BOXCTLMACRODEF_H_


/* 
copyright reserved by 
celtech company Co Ltd,
*/
 


#ifdef __cplusplus
extern "C" {
#endif



#define GBEMG_BOXCTL_SECTION_TABLE_ID_OFFSET (0)
#define GBEMG_BOXCTL_SECTION_LENGTH_OFFSET (1)
#define GBEMG_BOXCTL_VERSION_NUM_OFFSET (5)
#define GBEMG_BOXCTL_SECTION_NUM_OFFSET (6)
#define GBEMG_BOXCTL_LAST_SECTION_NUM_OFFSET (7)
#define GBEMG_BOXCTL_SIGNATURE_LEN_OFFSET (8)

#define GBEMG_BOXCTL_EBM_AREACODE_NUM_OFFSET (10)


#define GBEMG_BOXCTL_TABLE_HEADER_LENGTH  (11)




#define GBEMG_BOXCTL_SECTION_TABLE(buf) (U8)((buf[GBEMG_BOXCTL_SECTION_TABLE_ID_OFFSET]&0xFF))
#define GBEMG_BOXCTL_SECTION_LENGTH(buf) (TS_READ_16(&buf[GBEMG_BOXCTL_SECTION_LENGTH_OFFSET])&0xFFF)


#define GBEMG_BOXCTL_VERSION_NUM(buf)   (U8)((buf[GBEMG_BOXCTL_VERSION_NUM_OFFSET]>>1)&0x1F)

#define GBEMG_BOXCTL_SECTION_NUM(buf)   (U8)(buf[GBEMG_BOXCTL_SECTION_NUM_OFFSET]&0xFF)


#define GBEMG_BOXCTL_LAST_SECTION_NUM(buf) (U8)(buf[GBEMG_BOXCTL_LAST_SECTION_NUM_OFFSET]&0xFF)

#define GBEMG_BOXCTL_SIGNATURE_LEN(buf) (TS_READ_16(&buf[GBEMG_BOXCTL_SIGNATURE_LEN_OFFSET])&0xFFFF)

#define GBEMG_BOXCTL_EBM_AREACODE_NUM(buf)    (U8)(buf[GBEMG_BOXCTL_EBM_AREACODE_NUM_OFFSET]&0xFF)


/*the following macro based on the begining of the loop of the EBM Area Code_Number content */

#define GBEMG_BOXCTL_EBM_COVER_AREACODE_OFFSET (0)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_TOTALLEN_OFFSET  (6)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_TOTALNUM_OFFSET  (7)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_HEADER_LENGTH (8)


#define GBEMG_BOXCTL_EBM_CONTROL_INFO_TOTALLEN(buf)  (U8)(buf[GBEMG_BOXCTL_EBM_CONTROL_INFO_TOTALLEN_OFFSET]&0xFF)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_TOTALNUM(buf)  (U8)(buf[GBEMG_BOXCTL_EBM_CONTROL_INFO_TOTALNUM_OFFSET]&0xFF)


/* the following macro based on the begining of the loop of ebm control information */


#define GBEMG_BOXCTL_EBM_CONTROL_INFO_TAG_OFFSET  (0)


#define GBEMG_BOXCTL_EBM_CONTROL_INFO_LEN_OFFSET  (1)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_DATA_OFFSET  (2)


#define GBEMG_BOXCTL_EBM_CONTROL_INFO_TAG(buf) (U8)(buf[GBEMG_BOXCTL_EBM_CONTROL_INFO_TAG_OFFSET]&0xFF)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_LEN(buf) (U8)(buf[GBEMG_BOXCTL_EBM_CONTROL_INFO_LEN_OFFSET]&0xFF)

#define GBEMG_BOXCTL_EBM_CONTROL_INFO_DATA(buf) (U8*)(&buf[GBEMG_BOXCTL_EBM_CONTROL_INFO_DATA_OFFSET])


#ifdef __cplusplus
}
#endif

#else
#error "Multiple inclusions of gbemg_boxctlmacro.h"

#endif


