#ifndef USERTYPE_HPP
#define USERTYPE_HPP

#include "peg.hpp"

#define NEWMENU_BACKGRANOUD_COLOR BLUE
#define NEWMENU_BUTTON_TYPE       1
#define NEWMENU_BAR_TYPE          2
#define NEWMENU_Select_TYPE          3
#define NEWMENU_HELPWND_MAXPEGCHAR 200

/* Define the transparent color for PEG. This color must be initialized as transparent
   when initializing STOSD region */
#define PegTransparentColor BLUE

enum {
	TYPE_PEGBITMAPWINDOW = FIRST_USER_WINDOW_TYPE
};

enum {
	PM_REFRESH = FIRST_USER_MESSAGE,
	PM_KEYLEFT,
	PM_KEYRIGHT,
	PM_KEYUP,
	PM_KEYDOWN,
	PM_UPDATEVALUE,
	PM_REFRESHHELPWND,
	PM_HOME
};

enum {
	kAutoAdjustBitmapSize, /* window is adjusted to fit bitmap size */
	kCenterBitmap					 /* bitmap is centered in the window */
};

#define FIRST_USER_ID 1000
// enums for the Menu windows. They MUST be classified by level, from main menu to sub-sub menu
enum {
	MAIN_MENU_ID = FIRST_USER_ID,		// main menu
	PICTURE_MENU_ID,
	SOUND_MENU_ID,
	PROGRAM_MENU_ID,
	SUPERFUNCTION_MENU_ID,
	SUPERSETTING_MENU_ID,
	FACTORY_MENU_ID,
	VIDEO_MENU_ID,
	WHITEBALANCE_MENU_ID,
	GEOMETRY_MENU_ID,
	PROMPT_ID,
	HELP_ID,
	PROGRESSWINDOW_ID,
	TVANIMATEWINDOW_ID,
	TVSELECTWINDOW_ID,
	FIRST_POPUP_ID								// DO NOT REMOVE THIS LINE IT MUST BE THE LAST ONE OF THIS enum
};

// enums for the popups windows. It includes volume information such as volume bar and mute icons.
enum
{
	LAST_USER_ID = FIRST_POPUP_ID // this line MUST be the last one of the enum
}; /* to be used to define IDs in menus */

#define MaxNumberOfWindow LAST_USER_ID - FIRST_USER_ID
#define PegBlueTransparent 254 /* color 254 should be initialized as blue transparent */

/* This defititions are the STANDARD VGA color palette generated by the BitmapConverter tool
   The tool MUST be configured as follows :
   - NO OPTIMISATION FOR BITMAPS
   - Generate OPTIMAL PALETTE
   - Optimal palette configuration is :
      - Std palette from 101 to 116
      - optimal palette from 117 to 253
   - ENABLE Transparency, with UPPER LEFT COLOR */

const COLORVAL AP_MMI_BLACK           = 101;
const COLORVAL AP_MMI_RED             = 102;        
const COLORVAL AP_MMI_GREEN           = 103;
const COLORVAL AP_MMI_BROWN           = 104;        
const COLORVAL AP_MMI_BLUE            = 105;        
const COLORVAL AP_MMI_MAGENTA         = 106;
const COLORVAL AP_MMI_CYAN            = 107;
const COLORVAL AP_MMI_LIGHTGRAY       = 108;  
const COLORVAL AP_MMI_DARKGRAY        = 109;   
const COLORVAL AP_MMI_LIGHTRED        = 110;   
const COLORVAL AP_MMI_LIGHTGREEN      = 111; 
const COLORVAL AP_MMI_YELLOW          = 112;
const COLORVAL AP_MMI_LIGHTBLUE       = 113;  
const COLORVAL AP_MMI_LIGHTMAGENTA    = 114;
const COLORVAL AP_MMI_LIGHTCYAN       = 115;  
const COLORVAL AP_MMI_WHITE           = 116;

#endif