blankt.bmp   BlankTurn
board.bmp    Board
empty.bmp    Empty
gameover.bmp GameOver
p1blank.bmp  P1blank
p1lit.bmp    Player1Lit
p1med.bmp    Player1Medium
p1micro.bmp  Player1Micro
p2blank.bmp  Player2Blank
p2lit.bmp    Player2Lit
p2med.bmp    Player2Medium
p2micro.bmp  Player2Micro
play1v.bmp   Player1Volts
play2v.bmp   Player2Volts
player1.bmp  Player1
player1s.bmp Player1s
player1t.bmp Player1t
player2.bmp  Player2
player2s.bmp Player2s
player2t.bmp Player2t
logo.bmp     Logo
